### ISSUE TITLE
Unable to apply patch `eqnum`

### ISSUE THREAD

**Issue by gusbrs** [schlcht/microtype#19]
## Description

Since recently, the `eqnum` patch has been failing to apply with message "Unable to apply patch `eqnum' on input line X."

Some looking into it with `\ifpatchable` and `\tracingpatches` suggests the failure comes from the `\eqref` patch. My guess is that commit https://github.com/latex3/latex2e/commit/7c1184dc800f8902f279103660f118e5a82e62b0, which just made the latest kernel release, and made `\eqref` robust in `amsmath` is the culprit.

_Please also indicate the engine(s) with which the issue occurs: pdfTeX/LuaTeX/XeTeX_

As far as I can see, this is not engine related, but I've tested with `pdflatex`.

## Minimal example demonstrating the issue
```tex
\documentclass{article}

\usepackage{etoolbox}
\tracingpatches

\usepackage{amsmath}
\usepackage{microtype}

\begin{document}
Hello!
\end{document}
```
In the log we get:
```
[debug] analyzing '\eqref'
[debug] ++ control sequence is defined
[debug] ++ control sequence is a macro
[debug] -- macro cannot be retokenized cleanly
[debug] -> the macro may have been defined under a category
[debug]    code regime different from the current one
[debug] -> the replacement text may contain special control
[debug]    sequence tokens formed with \csname...\endcsname;
[debug] -> the replacement text may contain carriage return,
[debug]    newline, or similar characters
```

**Comment by schlcht** [comment]
Thanks for the report. This has already been in the dev version ([9f89a37f](https://github.com/schlcht/microtype/commit/9f89a37fc03e1ff9bb0749f9a6378fa45a327c66)). Either use that or add the following after loading microtype:

```
\makeatletter
\MT@redefine@patch{eqnum}{%
  \MT@patch@patch\tagform@{(}{\leftprotrusion{(}}%
  \MT@patch@patch\tagform@{)}{\rightprotrusion{)}}%
  \MT@ifdefined@n@TF{eqref }
    {\MT@exp@cs\MT@patch@patch{eqref }}{\MT@patch@patch\eqref}
       {\tagform@}{\@nameuse{MT@patch@saved@\string\tagform@}}%
}{}
\makeatother
```

**Comment by gusbrs** [comment]
Ah, far behind you! :)
Thank you!

Should I close this? Or do you prefer to keep it open until the next release to prevent other people having the same thought as I did?

**Comment by schlcht** [comment]
yes, I usually keep "fixed in dev" issues open until the next release

**Comment by schlcht** [comment]
... which just went to CTAN.

**Comment by bhomaidan1990** [comment]
Hi,

I'm using **Beamer** and the problem is still, I'm using **Overleaf**:  `PdfLaTex`, `Tex v: 2022`, can you please tell me how I can resolve this problem? thanks in advance.

Here is my **MWE**:
```tex
\documentclass[aspectratio=169, professionalfonts, t,xcolor=table]{beamer}

\usepackage[utf8]{inputenc}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage{hyperref}

\makeatletter
\MT@redefine@patch{eqnum}{%
  \MT@patch@patch\tagform@{(}{\leftprotrusion{(}}%
  \MT@patch@patch\tagform@{)}{\rightprotrusion{)}}%
  \MT@ifdefined@n@TF{eqref }
    {\MT@exp@cs\MT@patch@patch{eqref }}{\MT@patch@patch\eqref}
       {\tagform@}{\@nameuse{MT@patch@saved@\string\tagform@}}%
}{}
\makeatother

\microtypesetup{nopatch=footnote}
\makeatletter
\catcode`\#=12
  \MT@define@patch{footnote1}{%
    \@ifpackageloaded{hyperref}{%
      \MT@patch@patch\@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}%
      \MT@patch@patch\@footnotetext{\@empty\ignorespaces}{\@empty\ignorespaces\leftprotrusion}%
    }{%
      \@ifpackageloaded{scrkbase}
        {\MT@patch@patch\scr@saved@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}}
        {\MT@patch@patch\@footnotetext{\ignorespaces}{\ignorespaces\leftprotrusion}%
         \@ifclassloaded{memoir}
           {\MT@patch@patch\@footnotetext{\foottextfont #1}{\foottextfont\leftprotrusion #1}}
           {}}%
    }%
  }{}%
\catcode`\#=6
\makeatother


\begin{document}
Hi.
\end{document}
```
